spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./db'
    username: 'sa'
    password: 'password'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: '/console'
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: 'todo-app-client'
#            authorization-grant-type: 'authorization_code'
#            scope: 'openid'
#        provider:
#          keycloak:
#            issuer-uri: 'http://localhost:8180/realms/TodoApp'
##            user-name-attribute: 'preferred_username'
#      resourceserver:
#        jwt:
#          issuer-uri: 'http://localhost:8180/realms/TodoApp'
management:
  endpoints:
    web:
      exposure:
        include: '*'

#keycloak:
#  realm: TodoApp
#  auth-server-url: http://localhost:8180/auth
#  resource: todo-app-client
#  public-client: true
#  bearer-only: true